### ISSUE TITLE
Mind-map

### ISSUE THREAD

**Issue by nikitml** [Innopolis-University-Adv-Statistics/Interactive-Statistics-Notebooks#13]

**Comment by utihamartiwi** [comment]
When do we use t-test, z-test, F-test, and Kolmogorov-Smirnov?
![comparative analysis-1](https://user-images.githubusercontent.com/55295457/78504319-92357c80-7796-11ea-846d-ddcfcd22afb4.png)

**Comment by utihamartiwi** [comment]
What if we use categorical data (not numeric)? what if our data is not normally distributed? Use nonparametric test like this:
![Nonparametric n corre -1](https://user-images.githubusercontent.com/55295457/78504413-43d4ad80-7797-11ea-980f-9970234dc5e0.png)

**Comment by utihamartiwi** [comment]
What is relationship between binomial and bernoulli? Gamma and exponential? Chi-Square and F?
![Dist n power-1](https://user-images.githubusercontent.com/55295457/78504440-7bdbf080-7797-11ea-8ddc-5816bfeb6ca9.png)
